services:
  - type: web
    name: janbhasha
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    branch: master
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: JanBhasha
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:dfgE04TEdcEInAi0kC40xhdmaxP0TaYxbrgVXovmfJw=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://janbhasha.onrender.com
      - key: SESSION_SECURE_COOKIE
        value: false
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_URL
        value: mongodb+srv://janbhasha:janbhasha123@cluster0.badsxit.mongodb.net/janbhasha?retryWrites=true&w=majority&appName=Cluster0
      - key: DB_DATABASE
        value: janbhasha
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: VIEW_COMPILED_PATH
        value: /tmp
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: sync
      - key: TRANSLATION_PROVIDER
        value: google
      - key: TRANSLATION_API_KEY
        value: AIzaSyAq-Ls2TiRV7j5cDAOwjoi1DRJX7_aQ7X0
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: marketinghome672@gmail.com
      - key: MAIL_PASSWORD
        value: eecrkgqvtvmvoits
      - key: MAIL_FROM_ADDRESS
        value: marketinghome672@gmail.com
      - key: MAIL_FROM_NAME
        value: JanBhasha

